#!/usr/bin/env zsh
# Checks if there's a frame open
emacsclient -n -e "(if (> (length (frame-list)) 1) 't)" 2> /dev/null | grep t &> /dev/null
if [ "$?" -eq "1" ]; then
    emacsclient -a '' -nqc -e "(select-frame-set-input-focus (selected-frame))" "(delete-other-windows)" "$@" &> /dev/null
 exit
else
 emacsclient -nq -e "(select-frame-set-input-focus (selected-frame))" "(delete-other-windows)" "$@" &> /dev/null
 exit
fi
